# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1041dfc1d02a7379025b35b957c2cfdc"
name = "carttrnsapp"
application_url = "https://carttransapp.onrender.com"
embedded = true
handle = "carttrnsapp"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_cart_transforms,write_products"

[auth]
redirect_urls = ["https://carttransapp.onrender.com/auth/callback", "https://carttransapp.onrender.com/auth/shopify/callback", "https://carttransapp.onrender.com/api/auth/callback"]

[pos]
embedded = false
