api_version = "2025-07"

[[extensions]]
name = "t:name"
handle = "cart-transformer"
type = "function"
uid = "880efb62-6c5e-ad93-d249-9913aad3d9cb8bb0dbab"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
